INSERT INTO Genders(GenderName) VALUES ('Male')
INSERT INTO Genders(GenderName) VALUES ('Female')




INSERT INTO Cities(CityName, ProvinceId) VALUES('Quetta',1)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Turbat',1)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Chaman',1)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Gwadar',1)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Sibi',1)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Kalat',1)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Usta Mohammad',1)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Hub',1)

INSERT INTO Cities(CityName, ProvinceId) VALUES('Dera Ismail Khan',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Chitral',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Charsadda',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Battagram',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Batkhela',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Bannu',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Ayubia',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Abbottabad',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Haripur',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Kohat',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Lakki Marwat',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Nowshera',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Mansehra',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Mardan',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Peshawar',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Swabi',2)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Swat',2)

INSERT INTO Cities(CityName, ProvinceId) VALUES('Ahmadpur East',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Attock',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Bahawalnagar',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Bahawalpur',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Lahore',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Bhakkar',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('BureWala',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Chichawatni',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Chishtian',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Daska',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Sailkot',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Faisalabad',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Sargodha',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Sahiwal',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Okara',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Multan',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Jhelum',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Hasilpur',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Haroonabad',3)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Gujranwala',3)

INSERT INTO Cities(CityName, ProvinceId) VALUES('Karachi',4)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Ghotki',4)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Hyderabad',4)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Jamshoro',4)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Jacobabad',4)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Larkana',4)
INSERT INTO Cities(CityName, ProvinceId) VALUES('Mirpur Khas',4)